CREATE TABLE IF NOT EXISTS users (
	id				INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
	created_at		TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at		TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
	name			VARCHAR(250) NOT NULL,
	email			VARCHAR(250) NOT NULL UNIQUE,
	gender			VARCHAR(10) NOT NULL,
	password		TEXT NOT NULL,
	password_repeat	TEXT NOT NULL
)